apiVersion: apps/v1
kind: Deployment
metadata:
  name: directions-service
  namespace: driving-navigation
  labels:
    app: directions-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: directions-service
  template:
    metadata:
      labels:
        app: directions-service
    spec:
      containers:
      - name: directions-service
        image: openrouteservice/openrouteservice:latest@sha256:f512ffed154521d1cfa62bce57218523e9a15a3cb9a88d2f5db26980bcf72b11
        ports:
        - containerPort: 8080
        env:
        # If using persistent volumes, enable this env var to use persistent data rather than building fresh data on spin up
        # - name: BUILD_GRAPHS
        #   value: "False" 
        - name: JAVA_OPTS
          value: "-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
        - name: CATALINA_OPTS
          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=directions-service"
        volumeMounts:
        - name: graphs-volume
          mountPath: /ors-core/data/graphs
        - name: elevation-cache-volume
          mountPath: /ors-core/data/elevation_cache
        
      volumes:                    # OpenRouteService suggests these should be persistent volumes, but I am working in a 
      - name: graphs-volume       # WSL docker desktop environment, where local persistent volumes are not supported (yet)
        emptyDir: {}
      - name: elevation-cache-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: directions-service
  namespace: driving-navigation
  labels:
    app: directions-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: directions-service