apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: driving-navigation
  labels:
    app: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: mendhak/http-https-echo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: driving-navigation
  labels:
    app: echo-server
spec:
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP
  selector:
    app: echo-server