apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: nginx-rp-config
  namespace: driving-navigation
data:  
  nginx.conf: |
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    events {
        worker_connections 1024;
    }
    http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        error_log /var/log/nginx/error.log;
        gzip on;
        gzip_disable "msie6";
        include /etc/nginx/conf.d/default.conf;
    }
  default.conf: |
    server {
      listen 80;
      listen 443 ssl;
      ssl_certificate     /etc/ssl/tls.crt;
      ssl_certificate_key /etc/ssl/tls.key;
      server_name _;

      location / {
        proxy_pass http://echo-server:3000;
      }

      location /directions {
        proxy_pass http://directions-service/ors/v2/directions/driving-car;
      }
    }