apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: nginx-rp
  namespace: driving-navigation
  labels:
    app: nginx-rp
    category: reverse-proxy
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rp
  template:
    metadata:
      labels:
        app: nginx-rp
        category: reverse-proxy
    spec:
      containers:
      - name: nginx-rp
        image: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - name: nginx-rp-config-cm-vol
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-rp-config-cm-vol
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: nginx-rp-tls-secret-vol
          mountPath: /etc/ssl
          readOnly: true
      volumes:
      # https://medium.com/swlh/quick-fix-mounting-a-configmap-to-an-existing-volume-in-kubernetes-using-rancher-d01c472a10ad
      - configMap:
          name: nginx-rp-config
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: default.conf
            path: default.conf
        name: nginx-rp-config-cm-vol
      - name: nginx-rp-tls-secret-vol
        secret:
          secretName: driving-navigation-tls
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rp
  namespace: driving-navigation
  labels:
    app: nginx-rp
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30000
    name: http
  - port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30001
    name: https
  selector:
    app: nginx-rp